name: Python Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11.5
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests on Linux
        run: |
          python -m unittest discover -s backend/src/test -p "*_test.py"